use std::str::FromStr;

grammar;

pub Expr: i32 = {
    <l:Expr> "+" <r:MultExpr> => l + r,
    <l:Expr> "-" <r:MultExpr> => l - r,
    MultExpr,
};

pub MultExpr: i32 = {
    <l:MultExpr> "*" <r:ExpExpr> => l * r,
    ExpExpr,
};

pub ExpExpr: i32 = {
    <l:ExpExpr> "**" <r:Factor> => l.pow(r as u32),
    Factor,
};

pub Factor: i32 = {
    <n:Num> => n,
    "(" <e:Expr> ")" => e,
};

Num: i32 = <s:r"[0-9]+"> => i32::from_str(s).unwrap();