[package]
name = "parser"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
lalrpop-util = {version = "0.22.1", features = ["lexer", "unicode"]}
llvm-sys = "201"

[build-dependencies]
lalrpop = "0.22.1"